project_name: couture
release:
  github:
    owner: pandich
    name: couture
  draft: true

universal_binaries:
  - id: couture
    replace: true
    ids:
      - couture_darwin_amd64
      - couture_darwin_arm64
    hooks:
      post:
        - cmd: "codesign --deep --force --verbose --sign \"{{ .Env.CODESIGN_SIGN }}\" --entitlements {{ .Env.CODESIGN_ENTITLEMENTS }} --options=runtime dist/couture_darwin_all/couture"
        - cmd: codesign --verify --deep --strict --verbose dist/couture_darwin_all/couture
        - cmd: hdiutil create -volname Couture -srcfolder dist/couture_darwin_all/couture -ov -format UDZO dist/couture.dmg
        - cmd: xcrun notarytool submit dist/couture.dmg --key {{ .Env.NOTARY_KEY }} --key-id {{ .Env.NOTARY_KEY_ID }} --issuer {{ .Env.NOTARY_ISSUER }} --wait
          output: true
        - cmd: xcrun stapler staple dist/couture.dmg
        - cmd: xcrun stapler validate dist/couture.dmg
        - cmd: spctl -a -vvv -t install dist/couture_darwin_all/couture
          output: true

builds:
  - id: couture
    main: ./main.go
    binary: couture
    goos:
      - linux
      - windows
    goarch:
      - "amd64"
      - "arm64"
      - "386"
    ldflags:
      - -s -w

  - id: couture_darwin_amd64
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
    binary: dist/couture_darwin_amd64/couture

  - id: couture_darwin_arm64
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w
    binary: dist/couture_darwin_arm64/couture

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
