project_name: couture

builds:
  - id: couture
    main: ./main.go
    binary: couture
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - "amd64"
      - "arm64"
      - "386"
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - VERSION

release:
  github:
    owner: pandich
    name: couture
  draft: true

snapshot:
  name_template: "{{ .Tag }}-next"

env:
  - CGO_ENABLED=0
