# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Couture < Formula
  desc "Allows for tailing multiple event sources."
  homepage ""
  version "0.0.8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/gaggle-net/couture/releases/download/v0.0.8/couture_0.0.8_Darwin_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "98d09a15c8868855c9c0134d06d4ec69fab3f0b8c6024d59015a2617fe1b444d"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/gaggle-net/couture/releases/download/v0.0.8/couture_0.0.8_Darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "96bf6340237c3871c97438e2cbdb79a6a208aa1c840cdd241e47a16f3ac36a38"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/gaggle-net/couture/releases/download/v0.0.8/couture_0.0.8_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "408a7441df53169c6f8ae24f39c15b13619610f13b78e906b617bb0bfb40443d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/gaggle-net/couture/releases/download/v0.0.8/couture_0.0.8_Linux_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "c6dec07675f5109399b2dcb2328a9bb54c546e8d601e90a1e6f11399e77998de"
  end

  def install
    bin.install "couture"
  end
end
