direction: right

couture -> cmd: cli
couture -> event: event model
couture -> manager: application
couture -> source: event sources
couture -> sink: event display

# sink
sink -> color
sink -> layout
layout -> column
sink -> theme

# source
source -> aws
aws -> cloudformation
aws -> cloudwatch
aws -> s3
source -> pipe
pipe -> local
pipe -> ssh
source -> elasticsearch
