name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Specify the Go version you need

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest  # You can specify a version if needed
          args: release --rm-dist  # Remove the dist folder before running the release

      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This token is automatically provided by GitHub Actions
        run: goreleaser release --rm-dist
